In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
x = np.array(my_list)

In [4]:
type(x)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# for financial data, usually don't go pass 2D array

In [9]:
# create arrays

In [10]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# 0. indicates floating point number

In [15]:
type(1)

int

In [16]:
type(1.0)

float

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# evenly space numbers over specified intervals

In [24]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [27]:
# identity matrix: zeros with diag of 1

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# random library

In [38]:
np.random.rand(5,3)

array([[0.26652908, 0.08697157, 0.06748951],
       [0.66294802, 0.75337689, 0.64639085],
       [0.98268282, 0.22225117, 0.5893665 ],
       [0.92163057, 0.82269049, 0.54559278],
       [0.62441442, 0.65587623, 0.93905349]])

In [39]:
# sampling from a random storage distribution

In [41]:
np.random.randn(5,4)

array([[ 2.24396467, -0.6209051 , -3.20156488, -0.16781025],
       [ 0.22213224, -1.50183461,  1.18454652, -0.96483806],
       [-1.18559462,  0.41549462, -0.45045878, -1.25570409],
       [ 0.27488234,  0.46786729, -0.54945967,  0.64102587],
       [ 0.90323011,  0.02020386,  2.14422772, -0.85178106]])

In [45]:
np.random.randint(1,101,10)

array([ 7, 44, 25,  8, 57,  9, 84, 32, 35, 36])

In [46]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([ 1,  4,  7, 21, 45, 21, 19, 22, 14, 24])

In [49]:
# reshape array

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# shape attribute - shape of array

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr.reshape(25,1).shape

(25, 1)

In [66]:
arr.dtype

dtype('int64')

In [67]:
ranarr

array([ 1,  4,  7, 21, 45, 21, 19, 22, 14, 24])

In [70]:
ranarr.max()

45

In [71]:
ranarr.argmax()

4

In [72]:
ranarr.min()

1

In [73]:
ranarr.argmin()

0